# Generated by Django 4.0.7 on 2023-04-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='food',
            new_name='foods',
        ),
    ]
