# Generated by Django 4.0.7 on 2023-04-20 17:27

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('favs', '0002_comment_thing_comment_thing_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
